version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: nuget restore
build:
  project: shadowsocks-csharp.sln
  parallel: true
  verbosity: normal
after_build:
- cmd: 7z a ShadowsocksR.zip %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\ShadowsocksR.exe %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\ShadowsocksR.dll %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\ShadowsocksR.runtimeconfig.json
artifacts:
- path: ShadowsocksR.zip
  name: ShadowsocksR.zip
  