version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: nuget restore
build_script:
- cmd: build.cmd
after_build:
- cmd: >-    
    7z a ShadowsocksR-net48.zip %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\net48\ShadowsocksR.exe
test: off
artifacts:
- path: ShadowsocksR-net48.zip
  name: ShadowsocksR-net48.zip