version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: nuget restore
build_script:
- cmd: build.cmd
after_build:
- cmd: |
    7z a -mx9 ShadowsocksR-net48.7z %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\net48\ShadowsocksR.exe %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\net48\ShadowsocksR.exe.config
    7z a -mx9 ShadowsocksR-netcore.7z %APPVEYOR_BUILD_FOLDER%\shadowsocks-csharp\bin\Release\netcoreapp3.0\publish\
    7z rn ShadowsocksR-netcore.7z publish ShadowsocksR
test: off
artifacts:
- path: ShadowsocksR-netcore.7z
  name: ShadowsocksR-netcore.7z
- path: ShadowsocksR-net48.7z
  name: ShadowsocksR-net48.7z