on: [watch]

name: Telegram Notify Watch

jobs:

  build:
    runs-on: ubuntu-latest
    name: Telegram Notify Watch
    steps:
    - name: Telegram Notify Watch
      uses: appleboy/telegram-action@master
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_BOT }}
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO_MYSELF }}
      with:
        args: "{{ repo }}:\n多一个 star(｀・ω・´)"
