on: [release]

name: Telegram Notify Release

jobs:

  build:
    runs-on: ubuntu-latest
    name: Telegram Notify
    steps:
    - name: Telegram Notify
      uses: appleboy/telegram-action@master
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_BOT }}
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO_CHANNEL }}
      with:
        args: "{{ repo }}:\n 有新版本：{{ commit.ref }}(｀・ω・´)"
